### ISSUE TITLE
Impossible d'installer les modules necessaires

### ISSUE THREAD

**Issue by zb2oby** [Nash115/frenchATC-for-MSFS2020#19]
Bonjour,
Il m'est impossible de lancer le soft. Lorsque je lance atc.py, j'ai l'erreur : 

```
Informations météo délivrées par metar-taf.com
Impossible d'importer les modules nécessaires. Exécutez le programme 'libraries_installer.bat'.
Appuyez sur une touche pour continuer...
```

Voici la sortie du libraries_installer.bat qui semble bien fonctionner : 

> 
D:\frenchATC-for-MSFS2020(1-1-1)>echo off 
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Installing collected packages: argparse
Successfully installed argparse-1.4.0
####################
Requirement already satisfied: sounddevice in c:\python39\lib\site-packages (0.4.5)
Requirement already satisfied: CFFI>=1.0 in c:\python39\lib\site-packages (from sounddevice) (1.15.1)
Requirement already satisfied: pycparser in c:\python39\lib\site-packages (from CFFI>=1.0->sounddevice) (2.21)
####################
Requirement already satisfied: vosk in c:\python39\lib\site-packages (0.3.45)
Requirement already satisfied: srt in c:\python39\lib\site-packages (from vosk) (3.5.2)
Requirement already satisfied: websockets in c:\python39\lib\site-packages (from vosk) (10.4)
Requirement already satisfied: cffi>=1.0 in c:\python39\lib\site-packages (from vosk) (1.15.1)
Requirement already satisfied: requests in c:\python39\lib\site-packages (from vosk) (2.28.2)
Requirement already satisfied: tqdm in c:\python39\lib\site-packages (from vosk) (4.64.1)
Requirement already satisfied: pycparser in c:\python39\lib\site-packages (from cffi>=1.0->vosk) (2.21)
Requirement already satisfied: idna<4,>=2.5 in c:\python39\lib\site-packages (from requests->vosk) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\python39\lib\site-packages (from requests->vosk) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python39\lib\site-packages (from requests->vosk) (3.0.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python39\lib\site-packages (from requests->vosk) (1.26.14)
Requirement already satisfied: colorama in c:\python39\lib\site-packages (from tqdm->vosk) (0.4.6)
####################
Requirement already satisfied: colorama in c:\python39\lib\site-packages (0.4.6)
####################
Requirement already satisfied: gtts in c:\python39\lib\site-packages (2.3.1)
Requirement already satisfied: requests<3,>=2.27 in c:\python39\lib\site-packages (from gtts) (2.28.2)
Requirement already satisfied: click<8.2,>=7.1 in c:\python39\lib\site-packages (from gtts) (8.1.3)
Requirement already satisfied: colorama in c:\python39\lib\site-packages (from click<8.2,>=7.1->gtts) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python39\lib\site-packages (from requests<3,>=2.27->gtts) (3.0.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\python39\lib\site-packages (from requests<3,>=2.27->gtts) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python39\lib\site-packages (from requests<3,>=2.27->gtts) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in c:\python39\lib\site-packages (from requests<3,>=2.27->gtts) (3.4)
####################
Requirement already satisfied: requests in c:\python39\lib\site-packages (2.28.2)
Requirement already satisfied: idna<4,>=2.5 in c:\python39\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python39\lib\site-packages (from requests) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\python39\lib\site-packages (from requests) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python39\lib\site-packages (from requests) (3.0.1)
####################
Requirement already satisfied: bs4 in c:\python39\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\python39\lib\site-packages (from bs4) (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\python39\lib\site-packages (from beautifulsoup4->bs4) (2.3.2.post1)
####################
Requirement already satisfied: SimConnect in c:\python39\lib\site-packages (0.4.26)
Programme termine, les librairies ont du s'installer avec succes
Appuyez sur une touche pour continuer...

**Comment by zb2oby** [comment]
J'ai récupéré l'exception sur le message d'erreur (ce serai intéressant de le faire par défaut d'ailleurs avec un mode verbose ou autre ^^). 
Voici ce que j'ai : 
```'No module named 'sounddevice'```

Je ne connais pas Python du tout donc je n'irai pas plus loin mais est-il possible que finalement l'installation des librairies ne se soit pas correctement passée ?

**Comment by zb2oby** [comment]
J'ai résolu le problème. En fait le script atc.py ne se lançais pas avec la bonne version de python mais le script d'installation lui oui...désolé du dérangement.

**Comment by paulmrsr** [comment]
meme probleme pour moi mais je ne trouve pas de solutions, quelqu'un peux m'aider ?
![Capture d’écran 2023-06-11 103546](https://github.com/Nash115/frenchATC-for-MSFS2020/assets/136229299/f923a065-7a4c-4120-819f-95b9ff45b034)

**Comment by Nash115** [comment]
Bonjour, je pense savoir d'où vient le problème.
Durant votre installation python avez vous bien ajouté python.exe au "PATH" ?
[cliquez ici pour plus d'infos](https://github.com/Nash115/frenchATC-for-MSFS2020/wiki/Aide-pour-le-t%C3%A9l%C3%A9chargement,-l'installation-et-l'utilisation-du-mod#important--durant-linstallation-il-est-indispensable-dactiver-cela-)
Python est bien installé sur votre machine, cependant vous pouvez relancer le/un fichier d'installation de python et le réinstaller afin d'activer cette option...

Car en effet si cette option n'est pas activée il vous sera impossible d'installer les librairies

**Comment by paulmrsr** [comment]
effectivement le problème venait de la, encore merci. j'ai du lire les infos d'installations en travers

**Comment by Nash115** [comment]
Content que cela vous ai aidé
