### ISSUE TITLE
IMPOSSIBLE DE LANCER UN VOL

### ISSUE THREAD

**Issue by Nash115** [Nash115/frenchATC-for-MSFS2020#25]
**Il est actuellement impossible de lancer un vol, je travaille actuellement pour sortir une nouvelle mise à jour et corriger ce problème**

**Comment by paulmrsr** [comment]
est ce que ceci peux expliquer pourquoi je n'arrive pas a communiquer avec l'ATC ?

**Comment by Nash115** [comment]
Le problème a été corrigé dans le main. Des vérifications seront effectués et une nouvelle mise à jour sera disponible

**Comment by Nash115** [comment]
MAJ Disponible : V1.1.2
