### ISSUE TITLE
PTT

### ISSUE THREAD

**Issue by bloggisit** [Nash115/frenchATC-for-MSFS2020#28]
### Discussed in https://github.com/Nash115/frenchATC-for-MSFS2020/discussions/27

<div type='discussions-op-text'>

<sup>Originally posted by **bloggisit** August 31, 2023</sup>
bonjour, je ne sais pas activer le Push to Talk, jai un joystick saitek yoke mais je n'arrive pas a parler au controleur.</div>

**Comment by Nash115** [comment]
Bonjour, le programme ne possède pas de push to talk. Pour parler au contrôleur, il suffit de prononcer la phrase désirée, si elle contient le mot "Fox", elle sera analysée et vous obtiendrez une réponse ([plus d'infos](https://github.com/Nash115/frenchATC-for-MSFS2020/blob/main/phraseologie.txt))

Je vous conseille également de [mettre à jour](https://github.com/Nash115/frenchATC-for-MSFS2020/releases) le programme car un bug le rendait inutilisable
